version: "3.3"

services:

  maven_build:
    image: dgomes_websockets:0.1
    build:
      context: ./
      dockerfile: ./dockerfiles/maven_build/DockerFile

  spring_run:
    build:
      context: ./
      dockerfile: ./dockerfiles/spring_run/DockerFile
    command: java -jar dgomes_app.jar
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq

  rabbitmq:
    build:
      context: .
      dockerfile: ./dockerfiles/rabbitmq_stomp/DockerFile
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/ # creates one logging folder only, maps the full folder
    ports:
      - "61613:61613"
    restart: on-failure
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "61613" ]
      timeout: 5s
      retries: 1
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

volumes:
  rabbitmq_data:
