version: "3.3"

services:

  rabbitmq:
    build:
      context: .
      dockerfile: ./dockerfiles/rabbitmq_stomp/DockerFile
    hostname: rabbitmq # this way it always starts on the same hostname, preventing multiple log folders
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/ # creates one logging folder only, maps the full folder
    ports:
      - "61613:61613"
    restart: on-failure
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "61613" ]
      timeout: 5s
      retries: 1
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

volumes:
  rabbitmq_data:


